### ISSUE TITLE
Reuse Bokeh webdriver

### ISSUE THREAD

**Issue by bryevdv** [jonmmease/plotly_orca_notebooks#1]
Bokeh will also reuse a webdriver, if you ask. If you change your "Bokeh" cell to this:

```
from bokeh.io.export import create_webdriver
driver = create_webdriver()

def save_bokeh_png():
    p = bkplt.figure(toolbar_location=None, plot_width=figwidth, plot_height=figheight)

    p.scatter(x, y, 
              size=sz*30,
              fill_color=bkcolors,
              fill_alpha=0.5,
              line_color=None)
    bkio.export_png(p, filename="benchmarking/bokeh_fig.png", webdriver=driver)

def save_bokeh_svg():
    p = bkplt.figure(toolbar_location=None, plot_width=figwidth, plot_height=figheight, output_backend="svg")
    
    p.scatter(x, y, 
              size=sz*30,
              fill_color=bkcolors,
              fill_alpha=0.5,
              line_color=None)
    
    bkio.export_svgs(p, filename="benchmarking/bokeh_fig.svg", webdriver=driver)
```

You will see a noticeably different final result graph:

![dmioh_guwaaqogi](https://user-images.githubusercontent.com/1078448/45249606-f0a72a00-b2d7-11e8-96c4-6f5d2d0e7f55.jpg)

We would appreciate it if you update your notebook and post to reflect this usage.

**Comment by jonmmease** [comment]
Thanks for the full example @bryevdv, very cool.

I updated the notebook in https://github.com/jonmmease/plotly_orca_notebooks/commit/f51591c6d7936bfab978ad719aa56146de97854c and the blog post has been updated too.

**Comment by bryevdv** [comment]
Awesome, thanks!
